services:
  - type: web
    name: aetheris-backend
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free          # Cambia a "starter" si necesitas más recursos
    envVars:
      - key: MYSQL_HOST
        value: mysql-roberth.alwaysdata.net
      - key: MYSQL_DATABASE
        value: roberth_is
      - key: MYSQL_USER
        value: roberth
      - key: MYSQL_PASSWORD
        sync: false     # Se cargará como secret en el dashboard de Render
      - key: JWT_SECRET
        sync: false     # Se cargará como secret en el dashboard de Render
